sudo: required
language: bash
services:
- docker
env:
  global:
  - IMAGE_NAME=m3ki/mqtt-dasher
  REGISTRY_USER:
    secure: fUDW4X2EwdsAoJB0wFHBo0gyyyQuguAOE9KqxM7iRAsaNORoh78RlkFBPUyJdQssfGoDzJprhfpTAdh9RA7xKgwyb2gunphmGg781AW5E/w3A6o4MCxMFa8rmjdvOrie9TTQEID/v/28bJFJ00wKLBHB8gJ2LU3KxaDeRtUozgjH3BN6WcAo5RDIMtB/5suyk9xx4XauEpZjiGzHO4aH5sjsmsH/HA2ZXb5mfvT5N0VaDt9V1uoOiJ2X7NgkGUJex2CLqRBHc9849Xe6pdjx9s2hjoJP4NpgjFUlm4a7iaLmiDCr+TD1Aera26Fe0egZY/wwGmlTPpg1JxHGiILuqi49GNo296A4zJM2KEjveRGOOXUz+zz/pZB+ngHVNTWgu7fvlr38sqh8XTaPPvVSF49qmpogLSRdGd4Oce7T1ECp+AF7Vb+aSxndJs0Is8pzrhpJiwrI22rzUdn6YS1DSpFr6m7mg9cDqmpeJKfVtjCwyTLYu29eUHxxQE1bLuh9hDU2inmTnIimS0dawGej9impAn46aLCZDP5rKHJSj9x/gAmsVUm6mOBCW8B+HZHRkIv0vxgS4+hH0GykrBerQ8gaYQpurH9JDOL1O7cmco2AoE02S9Wck2dET67yjclNwpqv8PgTP1xfnhNSO6nd5c2GDieDoVpRaEU04hOogCQ=
  REGISTRY_PASS:
    secure: rPwzBxNLGPw36jlVMYFxJC/84SaGMk75HtWPMBvbWZOLZPo/9AFE3muVzmNE7vliALzLRIURy4lEi4tPTV4NXB6KMXP9LfaPEAi19nT5eI5LVZqILT1CUgWy3rBJ8EBBchKaVkaa36LiL2ap5gJnwqfnSZP58OUevrUwZK18jtejRQNEJg27EJftudeAZh4EMp7sPD/0xMPOBDJHCvMnAOtnFFuqviWBhIOuv9EuoZ4c68ZofXOLA8uYAYLs6aBvBvd81yEL+9zYgodiVmsjas657KgbN13OZVv0e7hhnPl/o7xbx+MnbMxE4vD1lQNk/wDYZMnDEMwwBbwPMHSRcRU1ukPRACXk8C6F+yTbvRnRA6JwQy++8sBO7RKF2bbxekJEdBwcqNucCHW5uj3OFL/uhyjKv17HBB/hrFP+xlEflXdXcJnEzEuHGgSUuE/tKmkMes0uKQkuIE4H7/nlr2d5T+QQC+1em5yZbu2/C197YHjQJffGNj9jidRWRMlC/Q1QJ6T0bPB46NcmiKFRHV+Xb7BxFU02aXGcLDJCnZqvWIKCbhsV4rimdPFyAKILd4TezaFCWPdtJ3j7U8jQw7iQ0NnVRBVVpBJvoPmHQe6xafRnQFGfPqjZTirO1oubgScBKnhQGQOTow2aolcMi30xGBZHE9hIg5yEb7ZJG14=
before_install:
- version=`./get-package-ver.sh`
- echo $version
- docker build -t "$IMAGE_NAME" .
- docker ps -a
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
after_script:
- docker images
