sudo: required
language: bash
services:
  - docker
env:
  global:
    - IMAGE_NAME=m3ki/mqtt-dasher
    - REGISTRY_USER=m3ki
    # REGISTRY_PASS=...
    - secret: "<something long>"

before_install:
  - version=`./get-package-ver.sh`
  - echo $version
  - docker build -t "$IMAGE_NAME" .
  # - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

after_script:
  - docker images

# before_deploy:
#   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
#   - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
#   - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
# deploy:
#   provider: script
#   script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
#   on:
#     branch: master
