---
mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: mqtt
    port: 1883
    #leave empty if none
    username:
    password:
    # Preface for the topics $PREFACE/$TOPIC
    preface: dash

buttons:
    44:65:0d:dc:51:50:
        name: nerf_supplies
        interface: eth0     # optional
        timeout: 5000   # optional (time in ms)
        protocol: arp   # optional (one of {udp, arp, all})
